# Created with komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Amazon.AWSCLI
PackageVersion: 2.31.25
InstallerLocale: en-US
Platform:
- Windows.Desktop
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- aws
ProductCode: '{860C9353-4F13-44AA-8438-1CA04C58CC2C}'
ReleaseDate: 2025-10-29
AppsAndFeaturesEntries:
- DisplayName: AWS Command Line Interface v2
  ProductCode: '{860C9353-4F13-44AA-8438-1CA04C58CC2C}'
  UpgradeCode: '{E1C1971C-384E-4D6D-8D02-F1AC48281CF8}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Amazon\AWSCLIV2'
Installers:
- Architecture: x64
  InstallerUrl: https://awscli.amazonaws.com/AWSCLIV2-2.31.25.msi
  InstallerSha256: 5A8204CD91A22BFE4DEC95D30AF51DEAAECB93E4F4F7E2B2077625F3E9587AC7
ManifestType: installer
ManifestVersion: 1.10.0
