# Created with komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: OBSProject.OBSStudio
PackageVersion: 32.0.2
PackageLocale: en-US
Publisher: OBS Project
PublisherUrl: https://obsproject.com/
PublisherSupportUrl: https://obsproject.com/help
Author: OBS Project
PackageName: OBS Studio
PackageUrl: https://obsproject.com/
License: GPL-2.0
LicenseUrl: https://github.com/obsproject/obs-studio/blob/master/COPYING
CopyrightUrl: https://github.com/obsproject/obs-studio/blob/master/COPYING
ShortDescription: Free and open source software for video recording and live streaming.
Moniker: obs
Tags:
- foss
- live
- recording
- screen-capture
- streaming
- video-recording
ReleaseNotes: |-
  32.0.2 Hotfix Changes
  - Fixed a crash on macOS when attempting to login with service integrations [PatTheMav]
  - Fixed an issue on macOS where Syphon Client sources could be blank/transparent [gxalpha]
  32.0.1 Hotfix Changes
  - Fixed a possible crash in 32.0.0 on Windows when opening source properties [wanhongqing123]
  - Fixed an issue in 32.0.0 where browser sources would break after switching scenes [tytan652]
    - This issue may also have caused increased resource usage.
  - Fixed an issue in 32.0.0 with the audio deduplication logic when an Audio Capture Source device is also used for monitoring [pkviet]
  - Fixed an issue in 32.0.0 where Multitrack Video settings were unavailable to Custom Services [PatTheMav]
  32.0 New Features
  - Added a basic plugin manager [FiniteSingularity/PatTheMav/Warchamp7]
  - Added opt-in automatic crash log upload for Windows and macOS [PatTheMav/Warchamp7]
  - Added Voice Activity Detection (VAD) to NVIDIA RTX Audio Effects, which improves noise suppression for speech, as well as several optimizations to NVIDIA Effects [pkviet]
  - Added chair removal option for NVIDIA RTX Background Removal, allowing removal of chairs [pkviet]
  - Added experimental Metal renderer for Apple Silicon Macs [PatTheMav]
  - Added Hybrid MOV support [derrod]
    - Brings ProRes support on macOS and a more widely supported HEVC/H.264 + PCM audio option to all platforms
  32.0 Changes
  - OBS Studio will no longer load plugins built for a newer release of OBS to prevent future compatibility issues [norihiro]
  - Added custom OBS widgets in preparation for larger UI updates [derrod/gxalpha/Warchamp7]
  - Added preparations for Metal renderer (stay tuned!) [PatTheMav]
  - Changed default bitrate from 2500 to 6000 Kbps [notr1ch]
  - Changed the crash sentinel file location to its own subdirectory [PatTheMav]
  - Improved audio deduplication logic to cover more cases of nested scenes, groups, and multiple canvases [pkviet]
  - Prevent audio duplication when sources are set to "Monitor and Output" while the monitoring device is also being captured [pkviet]
  - Updated the default settings for AMD encoders [rhutsAMD]
  - Improved accuracy of chapter markers in Hybrid MP4/MOV [derrod]
  - Re-hid the cursor in edit fields on macOS [gxalpha]
  - Improved format selection for PipeWire video capture [tytan652]
  - Removed workarounds to prevent loading Qt 5 based plugins [RytoEX]
  - Removed the --disable-shutdown-check launch flag [PatTheMav]
  - Hybrid MP4/MOV is now out of beta and has been made the default output format for new profiles [derrod]
  32.0 Bug Fixes
  - Potentially fixed a rare crash on macOS when moving or resizing the OBS window [PatTheMav]
  - Fixed a crash with SRT when using an invalid URL [pkviet]
  - Fixed a crash when setting non-default pkt_size with SRT [pkviet]
  - Fixed a crash in Media Source when playback starts with certain video files [howellrl]
  - Fixed a UI deadlock when opening source properties from the Sources list when the Windows setting 'Snap mouse to default button in dialog boxes' was enabled by adding a 200ms delay before creating the properties window [Warchamp7]
  - Fixed a memory leak when trying to output Hybrid MP4 to a non-writeable location [norihiro]
  - Fixed rare occurrence of multiview becoming blank [norihiro]
  - Fixed SRT reconnection failures [pkviet]
  - Fixed overflow texture rendering sRGB-awareness [PatTheMav]
  - Fixed incorrect color range property setting for AMD AV1 encoder [rhutsAMD]
  - Fixed Hybrid MP4 file splitting not working correctly in some cases [derrod]
  - Fixed not being able to capture higher than 60fps with macOS Screen Capture [jcm93]
  - Fixed focus not displaying properly in hotkey settings on macOS [gxalpha]
  - Fixed the scrollbar appearing invisible in Light and Rachni themes [shiina424]
  - Fixed HEVC frame priority not being set correctly in some cases, potentially causing playback errors when dropping frames [dsaedtler]
  - Fixed an issue that could result in increases to output latency after temporary encoder stalls [dsaedtler]
  - Fixed an issue where Multitrack Video could still be enabled after switching from a service that supports it to one that does not [Penwy]
  - Fixed an issue where GetGroupList with obs-websocket would return nothing [gxalpha]
  - Removed a workaround for older Qt versions that prevented docks from loading correctly while OBS is maximized [RytoEX]
  Checksums
  OBS-Studio-32.0.2-Sources.tar.gz: 48d744037c553eea8f9b76bf46f6dcac753e52871f49b2c1a2580757f723a1b7
  OBS-Studio-32.0.2-Ubuntu-24.04-x86_64-dbsym.ddeb: b7ef41ca56c072194a2b819108a92f0e71830eae4d6265b4f3cf62359b546d52
  OBS-Studio-32.0.2-Ubuntu-24.04-x86_64.deb: ab1ba6582fcc5eaf051f28fafc01becec5d8edabfe4775626d5a1c94ef6340bb
  OBS-Studio-32.0.2-Windows-arm64-PDBs.zip: 0a1b87d0a7e535876366cc45ca3aae769c6380223bcde40a9cc40852ace79a9e
  OBS-Studio-32.0.2-Windows-arm64.zip: 73a2958c4e5bf07f1479b5997ffcae6955848e160d61044d9e0f45d826cfb678
  OBS-Studio-32.0.2-Windows-x64-Installer.exe: da31c224edcb9520afa6a0df89c0cc32eac07b5d8e8bc2816c3e55764738a117
  OBS-Studio-32.0.2-Windows-x64-PDBs.zip: 1b3e913564866ea67db711ab4bb4e9ecd3225fb4bad478cf71b09ddaf98fe5ef
  OBS-Studio-32.0.2-Windows-x64.zip: 60b4510590140bd83625cc694d4ccd56b34fb499fc41d18c9558636a53ceabfa
  OBS-Studio-32.0.2-macOS-Apple-dSYMs.tar.xz: 260fd560655ff7351710351f8d08555ea52b7c9a95b188924f29676d1ffc592c
  OBS-Studio-32.0.2-macOS-Apple.dmg: 5c8f0e2349e45b57512e32312b053688e0b2bb9f0e8de8e7e24ee392e77a7cb3
  OBS-Studio-32.0.2-macOS-Intel-dSYMs.tar.xz: 6cd38a3013bae8b99c43f7edca5051b8d9639b30a1a7c70e7fe20ac5bbf39923
  OBS-Studio-32.0.2-macOS-Intel.dmg: ad5613bf36d95f8917fe56b127359b48595671e7341dc997202bb15242a53466
ReleaseNotesUrl: https://github.com/obsproject/obs-studio/releases/tag/32.0.2
Documentations:
- DocumentLabel: Wiki
  DocumentUrl: https://github.com/obsproject/obs-studio/wiki
ManifestType: defaultLocale
ManifestVersion: 1.10.0
