# Created with komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: OBSProject.OBSStudio
PackageVersion: 32.0.2
InstallerLocale: en-US
Platform:
- Windows.Desktop
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
ExpectedReturnCodes:
- InstallerReturnCode: 6
  ReturnResponse: packageInUseByApplication
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ProductCode: OBS Studio
ReleaseDate: 2025-10-23
AppsAndFeaturesEntries:
- ProductCode: OBS Studio
ElevationRequirement: elevatesSelf
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\obs-studio'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/obsproject/obs-studio/releases/download/32.0.2/OBS-Studio-32.0.2-Windows-x64-Installer.exe
  InstallerSha256: DA31C224EDCB9520AFA6A0DF89C0CC32EAC07B5D8E8BC2816C3E55764738A117
ManifestType: installer
ManifestVersion: 1.10.0
