# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: matchmycolor.ColibriAlpha
PackageVersion: 25.3.0.15910
InstallerType: exe
InstallerSwitches:
  Silent: /s
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.DotNet.Runtime.8
  - PackageIdentifier: Microsoft.DotNet.DesktopRuntime.8
  - PackageIdentifier: Microsoft.DotNet.AspNetCore.8
  - PackageIdentifier: Microsoft.VCRedist.2015+.x86
Installers:
- Architecture: x86
  InstallerUrl: https://cdn.matchmycolor.com/colibri/25.3.0/Colibri_25.3.0-alpha.235.exe
  InstallerSha256: C4CB38EE84862F2841AA765B32D23AF6435D8E50C213D51F7AE0F69B75CEE113
ManifestType: installer
ManifestVersion: 1.10.0
