# Created with komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: Flameshot.Flameshot
PackageVersion: 13.3.0
PackageLocale: en-US
Publisher: flameshot-org
PublisherUrl: https://flameshot.org/
PublisherSupportUrl: https://flameshot.org/docs
PackageName: Flameshot
PackageUrl: https://flameshot.org/
License: GPL-3.0
LicenseUrl: https://github.com/flameshot-org/flameshot/blob/HEAD/LICENSE
CopyrightUrl: https://github.com/flameshot-org/flameshot/blob/master/LICENSE
ShortDescription: Powerful yet simple to use screenshot software.
Moniker: flameshot
Tags:
- capture
- screenshot
- snipping
ReleaseNotes: |-
  What's Changed
  This is a hotfix for an issue preventing execution on MacOS
  - link to qtdbus on macos by @borgmanJeremy in #4325
  - Fix multiple memory leaks in Region::process() function by @avineet4 in #4284
  Full Changelog: v13.2.0...v13.3.0
ReleaseNotesUrl: https://github.com/flameshot-org/flameshot/releases/tag/v13.3.0
ManifestType: defaultLocale
ManifestVersion: 1.10.0
