# Created with komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Flameshot.Flameshot
PackageVersion: 13.3.0
InstallerLocale: en-US
InstallerType: wix
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
FileExtensions:
- bmp
- jpg
- png
ProductCode: '{8FA03992-037E-4A23-B8A8-AF2768116FBC}'
ReleaseDate: 2025-10-28
AppsAndFeaturesEntries:
- ProductCode: '{8FA03992-037E-4A23-B8A8-AF2768116FBC}'
  UpgradeCode: '{26D8062A-66D9-48D9-8924-42090FB9B3F9}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Flameshot'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/flameshot-org/flameshot/releases/download/v13.3.0/Flameshot-13.3.0-win64.msi
  InstallerSha256: 37CA5916450FAB003FB3C64EACD01D103D11D122C30BADE6AF144D4B0874DF66
ManifestType: installer
ManifestVersion: 1.10.0
